[project]
name = "machinelearning-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "numpy<2",
    "pandas>=2.3.1",
    "scikit-learn>=1.7.1",
    "scikit-surprise>=1.1.4",
]
